#production ready dockerfile for my refernces
#multi stage build for nodejs and nginx
FROM node:20-alphine AS builder
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.28-alphine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=30s \
            --timeout=5s \
            --start-period=10s \
            --retries=3 \
CMD wget --spider http://localhost/ || exit 1
CMD ["nginx" , "-g" , "daemon off;"]

# wget is a command-line utility used to make HTTP requests and download files.
# --spider means:

# Check whether the URL is accessible, but don't actually download the content.

# command1 || command2
# Run command2 only if command1 fails.
# exit 1
# means:

# Exit with a failure status.

# 0 generally means success, while a non-zero value means failure.

-------------------------------------------------------

# single stage build for python

FROM python:3.12-alphine
WORKDIR /app
COPY requirements.txt .
COPY app.py .
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "app.py"]