#production ready dockerfile for my refernces
#multi stage build for nodejs and nginx
FROM node:20-alphine AS builder
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.28-alphine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=30s \
            --timeout=5s \
            --start-period=10s \
            --retries=3 \
CMD wget --spider http://localhost/ || exit 1
CMD ["nginx" , "-g" , "daemon off;"]

-------------------------------------------------------

# single stage build for python

FROM python:3.12-alphine
WORKDIR /app
COPY requirements.txt .
COPY app.py .
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "app.py"]