name : cloning the code and setup the terraform   #workflow name
on :
  push : 
    branches : 
      - main
      - develop

jobs:
  terraform :                                       #job id
    name : code cloning and setup the terraform     #job name
    runs-on : ubuntu-latest
    steps :
          - name: clone the code
            uses: actions/checkout@v2

          - name: terraform setup
            uses: hashicorp/setup-terraform@v1

          - name: terraform initialzation
            run: terraform init

          - name: terraform validation
            run: terraform validate
          

     
